# https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ansible-create-complete-vm
#
# az group create --name edm-poc-eu-west --location westeurope

- name: Create Azure VM
  hosts: localhost
  connection: local

  roles:
    - set_azure_credentials
    - create_environment
    - create_vm

  tasks: []

- hosts: k8s_nodes
  tags:
    - k8s_all
  become: true

  roles:
#    #https://galaxy.ansible.com/pandemonium1986/k8s_toolbox
    - role: k9s
      tags: k9s
    - role: k8s
      tags: k8s
    - role: sys_manage_keys
      tags: ssh_keys

- hosts: k8s_nodes
  tags:
    - k8s_arc
  become: true

  roles:
    - configure_arc
