# https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ansible-create-complete-vm
#
# az group create --name edm-poc-eu-west --location westeurope

- name: Create Azure VM
  hosts: localhost
  connection: local


#xanmanning.k3s would form a cluster if play_hosts > 1 so we do it one-by-one
- hosts: k3s_nodes[0:1]
  become: true

  vars: []
    #k3s_flags: "--no-deploy traefik"

  roles:
    - role: xanmanning.k3s
      tags: k3s_nodes
      vars:
        k3s_become_for_all: true
        #k3s_flags: "--node-external-ip {{ inventory_hostname }}"

    #https://galaxy.ansible.com/pandemonium1986/k8s_toolbox
    - role: k9s
      tags: k9s

