---
# https://github.com/derailed/k9s
k9s_cache_path:        "/var/cache/github"
k9s_installation_path: "/opt/github/k9s"
k9s_checksum:          "sha256:d288aacc368ab6b243fc9e7ecd17b53fa34a813509c2dc3023171085db83cf9d"
k9s_version:           "v0.25.18"
