---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    k8s_kubeconfig: ~/.kube/k3s20.224.122.229
    k8s_manifests_base_dir: k8s-manifests/
    k8s_manifests:
      - storageclass
    k8s_resource_namespace: 'default'

  roles:
    - role: geerlingguy.k8s_manifests
